### ISSUE TITLE
Introduction of records V2

### ISSUE THREAD

**Issue by dr497** [Bonfida/sns-ip#4]
We are considering the introduction of a protocol to improve the handling of stale records and authenticity in SNS. Before drafting an SNS IP, we would like to discuss the broad strokes of our plan.

## Problem Statement:

Currently, when domain names are traded, the associated records can become stale, but still accessible. It also proves challenging to verify that the domain owner indeed owns the resources linked in the records which might lead to impersonation.

Staleness problem example:

- Alice owns something.sol
- Alice sets the URL record to https://google.com
- Alice sells something.sol to Bob
- The URL record is still set to https://google.com

Authenticity problem example:

- Alice Github handle is @alice
- Bob sets his Github record to @alice
- Alice sets her Github record to @alice
- dApps cannot know which user really owns @alice

## Proposed Solution:

1. **Staleness:** Require domain owners to sign a string composed of the record content and the record's public key when creating or updating a record. This signature will be invalidated when the domain ownership changes, effectively marking the associated record as stale.
2. **Authenticity:** Introduce an optional guardian system. This system will verify the user's ownership of a resource and provide a signature to be included in the record. Hence, the record's account will include the initial content, the staleness signature, and the guardian signature. Note that this is only relevant for certain records e.g Backpack record or Twitter record in order to prevent impersonation. Note that in certain cases (e.g ETH record) the user can be the guardian and self-sign the record.

The data structure of Records v2 is anticipated to be:

![state](https://clustain.sirv.com/sns-ip/state.png)

Existing records will need to be updated to include the new signature system. In order to be backwards compatible we propose adding a new derivation prefix to the record key: `\x02`

In order to be cross-chain compatible, the data structure for signatures consists of:

- A 1-byte signature enum: This is used to specify the type of signature, such as Ethereum, Solana, etc. This enum can be used to determine the length of the signature, as different blockchain systems might have signatures of different lengths.
- A variable length signature: The signature of the concatenation of the record's public key and the record's content either by the user or by the guardian.

## Expected Benefits:

1. Enhanced integrity of the domain name service through the identification and handling of stale records.
2. Improved confidence in resource authenticity through verification from a guardian system.

## Anticipated Challenges:

1. How should dApps handle the transition period?
2. Should records v1 be entirely deprecated?

We would appreciate your thoughts on this proposed solution and any potential challenges we might face. Any alternative ideas are also welcome. Once we gather enough input, we'll proceed to draft a detailed SNS IP.

Thank you in advance for your valuable insights.

![diagram](https://clustain.sirv.com/sns-ip/Records%20v2.png)

**Comment by ellttBen** [comment]
An implicit choice was made to make the record structure as simple and compatible as possible with the Borsh serialization standard. The question we should ask ourselves is whether or not we want to favor the simplicity of the Borsh standard over something that's more efficient to parse through direct type-casting methods.
In this case, this means that the Record `struct` definition needs to respect certain byte alignment constraints. In the case of the Solana BPF architecture, we'd want to 8-byte align most fields.
Here is an example of a proposed schema which properly aligns all fields that might require it :
```
 0                   1                   2                   3                   4                   5                   6       
 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|      User Signature Type      |    Guardian Signature Type    |                        Content-Length                         |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|                                                                                                                               |
+                                                        User signature                                                         +
                                                               ...                                                               
+                                                          (U*8 bytes)                                                          +
|                                                                                                                               |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|                                                                                                                               |
+                                                      Guardian signature                                                       +
                                                               ...                                                               
+                                                          (G*8 bytes)                                                          +
|                                                                                                                               |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|                                                                                                                               |
+                                                        Record Content                                                         +
                                                               ...                                                               
+                                                          (C*8 bytes)                                                          +
|                                                                                                                               |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
```
